# Generated by Django 5.2 on 2025-05-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tenant name', max_length=250)),
                ('vat_id', models.CharField(blank=True, help_text='Tenant VATID', max_length=20, null=True)),
                ('street_and_number', models.CharField(blank=True, help_text='Tenant address street with number', max_length=250, null=True)),
                ('postal_number', models.CharField(blank=True, help_text='Tenant address postal number', max_length=50, null=True)),
                ('city', models.CharField(blank=True, help_text='Tenant address city', max_length=150, null=True)),
                ('country', models.CharField(help_text='Tenant address country', max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
