# Generated by Django 5.2 on 2025-04-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingredient name', max_length=150)),
                ('code', models.CharField(help_text='Ingredient code', max_length=10)),
            ],
        ),
    ]
