# Generated by Django 5.2 on 2025-04-25 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingredient name', max_length=150)),
                ('code', models.CharField(help_text='Ingredient code', max_length=10)),
                ('description', models.CharField(blank=True, help_text='Ingredient description', max_length=500, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('1.00'), help_text='Ingredient base price', max_digits=18, null=True)),
                ('price_mod', models.DecimalField(blank=True, decimal_places=3, default=Decimal('1.00'), help_text='Ingredient price modification index', max_digits=5, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('1.00'), help_text='Ingredient final price', max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
