# Generated by Django 5.2 on 2025-05-05 16:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('1.00'), help_text='Product base price', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='PPP-000', help_text='Product code', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, help_text='Product description', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('1.00'), help_text='Product final price', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fixed_costs',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('1.00'), help_text='Product fixed production costs', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_from_products',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='No Product Name', help_text='Product name', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='price_mod',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('1.00'), help_text='Product price modification index', max_digits=5, null=True),
        ),
    ]
